! Generated by c68 4.5 20 Mar 99 (Wed Oct 27 11:15:06 1999) from "/tmp/c68071300.i"
	.sect	.text
	.sect	.rom
	.sect	.data
	.sect	.bss
	.sect	.text
	.align	2
I_1:
	.data4	0x3FF33333,0x33333333
	.align	2
	.extern _test
_test:
	bra	I_2
I_3:
	move.l	I_1+0,-8(a6)
	move.l	I_1+4,-4(a6)
	and.w	#0,-16(a6)
	or.w	#10,-16(a6)
	move.l	-4(a6),-(a7)
	move.l	-8(a6),-(a7)
	move.w	#4112,-(a7)
	pea	-16(a6)
	jsr	.Yasmuldf
	move.w	-16(a6),d0
	ext.l	d0
	move.l	d0,-12(a6)
I_4:
	unlk	a6
	rts
I_2:
	link	a6,#-16
	bra	I_3
